# Generated by Django 6.0.3 on 2026-03-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_residuos', '0002_zona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zona',
        ),
    ]
