# Generated by Django 6.0.3 on 2026-03-23 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_residuos', '0003_delete_zona'),
        ('logistica', '0010_puntorecogida_gestor_puntorecogida_transportista'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='transportista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='logistica.transportista'),
        ),
    ]
