# Generated by Django 6.0.3 on 2026-04-01 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ajustes', '0015_alter_conceptofacturable_cantidad_adicional_and_more'),
        ('logistica', '0010_puntorecogida_gestor_puntorecogida_transportista'),
        ('operativa', '0013_remove_lineapedido_observaciones_recogida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(default='FAC', max_length=10, verbose_name='Serie')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Número de factura')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDA', 'Emitida'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('base_imponible', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Base imponible')),
                ('cuota_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cuota de impuesto')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('albaranes', models.ManyToManyField(blank=True, related_name='facturas', to='operativa.albaran', verbose_name='Albaranes')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='logistica.cliente', verbose_name='Cliente')),
                ('impuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ajustes.impuesto', verbose_name='Impuesto')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='LineaFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('importe', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Importe')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='facturacion.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Línea de Factura',
                'verbose_name_plural': 'Líneas de Factura',
            },
        ),
    ]
