# Generated by Django 6.0.3 on 2026-03-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre / Razón Social')),
                ('cif_nif', models.CharField(max_length=20, verbose_name='CIF/NIF')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('localidad', models.CharField(max_length=100, verbose_name='Localidad')),
                ('cp', models.CharField(max_length=10, verbose_name='C.P.')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('nima', models.CharField(help_text='Número de Identificación Medioambiental', max_length=30, verbose_name='NIMA')),
                ('reg', models.CharField(help_text='Registro de transportista de residuos', max_length=50, verbose_name='Nº Registro')),
                ('ecoeffort', models.BooleanField(default=True, verbose_name='¿Es EcoEffort?')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
            ],
            options={
                'verbose_name': 'Transportista',
                'verbose_name_plural': 'Transportistas',
            },
        ),
    ]
