# Generated by Django 6.0.3 on 2026-03-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportista',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Identificación del Transportista'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='provincia',
            field=models.CharField(choices=[('Alava', 'Álava'), ('Albacete', 'Albacete'), ('Alicante', 'Alicante'), ('Almeria', 'Almería'), ('Asturias', 'Asturias'), ('Avila', 'Ávila'), ('Badajoz', 'Badajoz'), ('Barcelona', 'Barcelona'), ('Burgos', 'Burgos'), ('Caceres', 'Cáceres'), ('Cadiz', 'Cádiz'), ('Cantabria', 'Cantabria'), ('Castellon', 'Castellón'), ('Ciudad Real', 'Ciudad Real'), ('Cordoba', 'Córdoba'), ('La Coruña', 'La Coruña'), ('Cuenca', 'Cuenca'), ('Gerona', 'Gerona'), ('Granada', 'Granada'), ('Guadalajara', 'Guadalajara'), ('Guipuzcoa', 'Guipúzcoa'), ('Huelva', 'Huelva'), ('Huesca', 'Huesca'), ('Islas Baleares', 'Islas Baleares'), ('Jaen', 'Jaén'), ('Leon', 'León'), ('Lerida', 'Lérida'), ('Lugo', 'Lugo'), ('Madrid', 'Madrid'), ('Malaga', 'Málaga'), ('Murcia', 'Murcia'), ('Navarra', 'Navarra'), ('Orense', 'Orense'), ('Palencia', 'Palencia'), ('Las Palmas', 'Las Palmas'), ('Pontevedra', 'Pontevedra'), ('La Rioja', 'La Rioja'), ('Salamanca', 'Salamanca'), ('Segovia', 'Segovia'), ('Sevilla', 'Sevilla'), ('Soria', 'Soria'), ('Tarragona', 'Tarragona'), ('Santa Cruz de Tenerife', 'Santa Cruz de Tenerife'), ('Teruel', 'Teruel'), ('Toledo', 'Toledo'), ('Valencia', 'Valencia'), ('Valladolid', 'Valladolid'), ('Vizcaya', 'Vizcaya'), ('Zamora', 'Zamora'), ('Zaragoza', 'Zaragoza'), ('Ceuta', 'Ceuta'), ('Melilla', 'Melilla')], default='Madrid', max_length=100, verbose_name='Provincia'),
        ),
    ]
