# Generated by Django 6.0.3 on 2026-03-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0003_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestorResiduos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre / Razón Social')),
                ('cif_nif', models.CharField(max_length=20, verbose_name='CIF/NIF')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('localidad', models.CharField(max_length=100, verbose_name='Localidad')),
                ('cp', models.CharField(max_length=10, verbose_name='C.P.')),
                ('provincia', models.CharField(choices=[('Alava', 'Álava'), ('Albacete', 'Albacete'), ('Alicante', 'Alicante'), ('Almeria', 'Almería'), ('Asturias', 'Asturias'), ('Avila', 'Ávila'), ('Badajoz', 'Badajoz'), ('Barcelona', 'Barcelona'), ('Burgos', 'Burgos'), ('Caceres', 'Cáceres'), ('Cadiz', 'Cádiz'), ('Cantabria', 'Cantabria'), ('Castellon', 'Castellón'), ('Ciudad Real', 'Ciudad Real'), ('Cordoba', 'Córdoba'), ('La Coruña', 'La Coruña'), ('Cuenca', 'Cuenca'), ('Gerona', 'Gerona'), ('Granada', 'Granada'), ('Guadalajara', 'Guadalajara'), ('Guipuzcoa', 'Guipúzcoa'), ('Huelva', 'Huelva'), ('Huesca', 'Huesca'), ('Islas Baleares', 'Islas Baleares'), ('Jaen', 'Jaén'), ('Leon', 'León'), ('Lerida', 'Lérida'), ('Lugo', 'Lugo'), ('Madrid', 'Madrid'), ('Malaga', 'Málaga'), ('Murcia', 'Murcia'), ('Navarra', 'Navarra'), ('Orense', 'Orense'), ('Palencia', 'Palencia'), ('Las Palmas', 'Las Palmas'), ('Pontevedra', 'Pontevedra'), ('La Rioja', 'La Rioja'), ('Salamanca', 'Salamanca'), ('Segovia', 'Segovia'), ('Sevilla', 'Sevilla'), ('Soria', 'Soria'), ('Tarragona', 'Tarragona'), ('Santa Cruz de Tenerife', 'Santa Cruz de Tenerife'), ('Teruel', 'Teruel'), ('Toledo', 'Toledo'), ('Valencia', 'Valencia'), ('Valladolid', 'Valladolid'), ('Vizcaya', 'Vizcaya'), ('Zamora', 'Zamora'), ('Zaragoza', 'Zaragoza'), ('Ceuta', 'Ceuta'), ('Melilla', 'Melilla')], default='Madrid', max_length=100, verbose_name='Provincia')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('nima', models.CharField(help_text='Número de Identificación Medioambiental', max_length=30, verbose_name='NIMA')),
                ('reg', models.CharField(max_length=50, verbose_name='Nº Registro / Autorización')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
            ],
            options={
                'verbose_name': 'Gestor de Residuos',
                'verbose_name_plural': 'Gestores de Residuos',
            },
        ),
    ]
