# Generated by Django 6.0.3 on 2026-03-13 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0013_alter_datosconfigurables_valor'),
        ('logistica', '0004_gestorresiduos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('razon_social', models.CharField(max_length=150, verbose_name='Razón Social')),
                ('cif', models.CharField(max_length=20, verbose_name='CIF')),
                ('email_fiscal', models.EmailField(max_length=254, verbose_name='Email Fiscal')),
                ('direccion_fiscal', models.CharField(max_length=200, verbose_name='Dirección Fiscal')),
                ('numero_fiscal', models.CharField(max_length=10, verbose_name='Número Fiscal')),
                ('localidad_fiscal', models.CharField(max_length=100, verbose_name='Localidad Fiscal')),
                ('cp_fiscal', models.CharField(max_length=10, verbose_name='C.P. Fiscal')),
                ('provincia_fiscal', models.CharField(choices=[('Alava', 'Álava'), ('Albacete', 'Albacete'), ('Alicante', 'Alicante'), ('Almeria', 'Almería'), ('Asturias', 'Asturias'), ('Avila', 'Ávila'), ('Badajoz', 'Badajoz'), ('Barcelona', 'Barcelona'), ('Burgos', 'Burgos'), ('Caceres', 'Cáceres'), ('Cadiz', 'Cádiz'), ('Cantabria', 'Cantabria'), ('Castellon', 'Castellón'), ('Ciudad Real', 'Ciudad Real'), ('Cordoba', 'Córdoba'), ('La Coruña', 'La Coruña'), ('Cuenca', 'Cuenca'), ('Gerona', 'Gerona'), ('Granada', 'Granada'), ('Guadalajara', 'Guadalajara'), ('Guipuzcoa', 'Guipúzcoa'), ('Huelva', 'Huelva'), ('Huesca', 'Huesca'), ('Islas Baleares', 'Islas Baleares'), ('Jaen', 'Jaén'), ('Leon', 'León'), ('Lerida', 'Lérida'), ('Lugo', 'Lugo'), ('Madrid', 'Madrid'), ('Malaga', 'Málaga'), ('Murcia', 'Murcia'), ('Navarra', 'Navarra'), ('Orense', 'Orense'), ('Palencia', 'Palencia'), ('Las Palmas', 'Las Palmas'), ('Pontevedra', 'Pontevedra'), ('La Rioja', 'La Rioja'), ('Salamanca', 'Salamanca'), ('Segovia', 'Segovia'), ('Sevilla', 'Sevilla'), ('Soria', 'Soria'), ('Tarragona', 'Tarragona'), ('Santa Cruz de Tenerife', 'Santa Cruz de Tenerife'), ('Teruel', 'Teruel'), ('Toledo', 'Toledo'), ('Valencia', 'Valencia'), ('Valladolid', 'Valladolid'), ('Vizcaya', 'Vizcaya'), ('Zamora', 'Zamora'), ('Zaragoza', 'Zaragoza'), ('Ceuta', 'Ceuta'), ('Melilla', 'Melilla')], max_length=100, verbose_name='Provincia Fiscal')),
                ('observaciones_fiscal', models.TextField(blank=True, null=True, verbose_name='Observaciones Fiscales')),
                ('email_facturacion', models.EmailField(max_length=254, verbose_name='Email Facturación')),
                ('direccion_facturacion', models.CharField(max_length=200, verbose_name='Dirección Facturación')),
                ('numero_facturacion', models.CharField(max_length=10, verbose_name='Número Facturación')),
                ('localidad_facturacion', models.CharField(max_length=100, verbose_name='Localidad Facturación')),
                ('cp_facturacion', models.CharField(max_length=10, verbose_name='C.P. Facturación')),
                ('provincia_facturacion', models.CharField(choices=[('Alava', 'Álava'), ('Albacete', 'Albacete'), ('Alicante', 'Alicante'), ('Almeria', 'Almería'), ('Asturias', 'Asturias'), ('Avila', 'Ávila'), ('Badajoz', 'Badajoz'), ('Barcelona', 'Barcelona'), ('Burgos', 'Burgos'), ('Caceres', 'Cáceres'), ('Cadiz', 'Cádiz'), ('Cantabria', 'Cantabria'), ('Castellon', 'Castellón'), ('Ciudad Real', 'Ciudad Real'), ('Cordoba', 'Córdoba'), ('La Coruña', 'La Coruña'), ('Cuenca', 'Cuenca'), ('Gerona', 'Gerona'), ('Granada', 'Granada'), ('Guadalajara', 'Guadalajara'), ('Guipuzcoa', 'Guipúzcoa'), ('Huelva', 'Huelva'), ('Huesca', 'Huesca'), ('Islas Baleares', 'Islas Baleares'), ('Jaen', 'Jaén'), ('Leon', 'León'), ('Lerida', 'Lérida'), ('Lugo', 'Lugo'), ('Madrid', 'Madrid'), ('Malaga', 'Málaga'), ('Murcia', 'Murcia'), ('Navarra', 'Navarra'), ('Orense', 'Orense'), ('Palencia', 'Palencia'), ('Las Palmas', 'Las Palmas'), ('Pontevedra', 'Pontevedra'), ('La Rioja', 'La Rioja'), ('Salamanca', 'Salamanca'), ('Segovia', 'Segovia'), ('Sevilla', 'Sevilla'), ('Soria', 'Soria'), ('Tarragona', 'Tarragona'), ('Santa Cruz de Tenerife', 'Santa Cruz de Tenerife'), ('Teruel', 'Teruel'), ('Toledo', 'Toledo'), ('Valencia', 'Valencia'), ('Valladolid', 'Valladolid'), ('Vizcaya', 'Vizcaya'), ('Zamora', 'Zamora'), ('Zaragoza', 'Zaragoza'), ('Ceuta', 'Ceuta'), ('Melilla', 'Melilla')], max_length=100, verbose_name='Provincia Facturación')),
                ('observaciones_facturacion', models.TextField(blank=True, null=True, verbose_name='Observaciones Facturación')),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('fecha_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajustes.fechapago', verbose_name='Día de Pago')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
