# Generated by Django 6.0.3 on 2026-03-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0005_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='mismos_datos',
            field=models.BooleanField(default=False, verbose_name='¿Datos de facturación iguales a los fiscales?'),
        ),
    ]
