# Generated by Django 6.0.3 on 2026-03-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0006_cliente_mismos_datos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='mismos_datos',
            field=models.BooleanField(default=True, verbose_name='¿Usar mismos datos que los fiscales?'),
        ),
    ]
