# Generated by Django 6.0.3 on 2026-03-13 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0013_alter_datosconfigurables_valor'),
        ('logistica', '0008_subcliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoRecogida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre / Razón Social')),
                ('cif', models.CharField(max_length=20, verbose_name='CIF/NIF')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('localidad', models.CharField(max_length=100, verbose_name='Localidad')),
                ('cp', models.CharField(max_length=10, verbose_name='C.P.')),
                ('provincia', models.CharField(choices=[('Alava', 'Álava'), ('Albacete', 'Albacete'), ('Alicante', 'Alicante'), ('Almeria', 'Almería'), ('Asturias', 'Asturias'), ('Avila', 'Ávila'), ('Badajoz', 'Badajoz'), ('Barcelona', 'Barcelona'), ('Burgos', 'Burgos'), ('Caceres', 'Cáceres'), ('Cadiz', 'Cádiz'), ('Cantabria', 'Cantabria'), ('Castellon', 'Castellón'), ('Ciudad Real', 'Ciudad Real'), ('Cordoba', 'Córdoba'), ('La Coruña', 'La Coruña'), ('Cuenca', 'Cuenca'), ('Gerona', 'Gerona'), ('Granada', 'Granada'), ('Guadalajara', 'Guadalajara'), ('Guipuzcoa', 'Guipúzcoa'), ('Huelva', 'Huelva'), ('Huesca', 'Huesca'), ('Islas Baleares', 'Islas Baleares'), ('Jaen', 'Jaén'), ('Leon', 'León'), ('Lerida', 'Lérida'), ('Lugo', 'Lugo'), ('Madrid', 'Madrid'), ('Malaga', 'Málaga'), ('Murcia', 'Murcia'), ('Navarra', 'Navarra'), ('Orense', 'Orense'), ('Palencia', 'Palencia'), ('Las Palmas', 'Las Palmas'), ('Pontevedra', 'Pontevedra'), ('La Rioja', 'La Rioja'), ('Salamanca', 'Salamanca'), ('Segovia', 'Segovia'), ('Sevilla', 'Sevilla'), ('Soria', 'Soria'), ('Tarragona', 'Tarragona'), ('Santa Cruz de Tenerife', 'Santa Cruz de Tenerife'), ('Teruel', 'Teruel'), ('Toledo', 'Toledo'), ('Valencia', 'Valencia'), ('Valladolid', 'Valladolid'), ('Vizcaya', 'Vizcaya'), ('Zamora', 'Zamora'), ('Zaragoza', 'Zaragoza'), ('Ceuta', 'Ceuta'), ('Melilla', 'Melilla')], max_length=100, verbose_name='Provincia')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de Contacto')),
                ('telefono1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono 1')),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono 2')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_recogida', to='logistica.cliente', verbose_name='Cliente')),
                ('subcliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_recogida', to='logistica.subcliente', verbose_name='Subcliente')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ajustes.zona', verbose_name='Zona Logística')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
