# Generated by Django 6.0.3 on 2026-03-13 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0009_puntorecogida'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntorecogida',
            name='gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistica.gestorresiduos', verbose_name='Gestor de Residuos Destino'),
        ),
        migrations.AddField(
            model_name='puntorecogida',
            name='transportista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistica.transportista', verbose_name='Transportista Habitual'),
        ),
    ]
