# Generated by Django 6.0.3 on 2026-03-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Fecha de pago')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Opción activa?')),
            ],
            options={
                'verbose_name': 'Fecha de pago',
                'verbose_name_plural': 'Fechas de pago',
            },
        ),
        migrations.AlterField(
            model_name='zona',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Zona activa?'),
        ),
    ]
