# Generated by Django 6.0.3 on 2026-03-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0003_impuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Denominación')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activa?')),
            ],
            options={
                'verbose_name': 'Periodicidad',
                'verbose_name_plural': 'Periodicidades',
            },
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Detalle del Impuesto'),
        ),
    ]
