# Generated by Django 6.0.3 on 2026-03-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0004_periodicidad_alter_impuesto_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoFacturable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Concepto')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Base (€)')),
                ('texto_adicional', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto Adicional')),
                ('precio_adicional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Adicional (€)')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
            ],
            options={
                'verbose_name': 'Concepto Facturable',
                'verbose_name_plural': 'Conceptos Facturables',
            },
        ),
    ]
