# Generated by Django 6.0.3 on 2026-03-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0005_conceptofacturable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEnvase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Envase')),
                ('capacidad', models.CharField(max_length=50, verbose_name='Capacidad (ej: 200L, 1m³)')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Alquiler/Venta (€)')),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('especial', 'Especial')], default='normal', max_length=10, verbose_name='Tipo de Envase')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
            ],
            options={
                'verbose_name': 'Tipo de Envase',
                'verbose_name_plural': 'Tipos de Envases',
            },
        ),
    ]
