# Generated by Django 6.0.3 on 2026-03-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0006_tipoenvase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoenvase',
            name='capacidad',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True, verbose_name='Capacidad en litros'),
        ),
    ]
