# Generated by Django 6.0.3 on 2026-03-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0007_alter_tipoenvase_capacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoenvase',
            name='capacidad',
            field=models.CharField(max_length=10, null=True, verbose_name='Capacidad en litros'),
        ),
    ]
