# Generated by Django 6.0.3 on 2026-03-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0009_alter_tipoenvase_capacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoenvase',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Alquiler/Venta (€)'),
        ),
    ]
