# Generated by Django 6.0.3 on 2026-03-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0010_alter_tipoenvase_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoResiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ler', models.CharField(max_length=20, verbose_name='Código LER')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Residuo')),
                ('precio_kg', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Precio por Kg (€)')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
            ],
            options={
                'verbose_name': 'Tipo de Residuo',
                'verbose_name_plural': 'Tipos de Residuos',
            },
        ),
        migrations.AlterField(
            model_name='conceptofacturable',
            name='precio_adicional',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Precio Adicional (€)'),
        ),
        migrations.AlterField(
            model_name='conceptofacturable',
            name='precio_base',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Precio Base (€)'),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='valor',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Valor (%)'),
        ),
        migrations.AlterField(
            model_name='tipoenvase',
            name='precio',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Precio Alquiler/Venta (€)'),
        ),
    ]
