# Generated by Django 6.0.3 on 2026-03-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0011_tiporesiduo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosConfigurables',
            fields=[
                ('clave', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Nombre de la Variable')),
                ('valor', models.TextField(verbose_name='Valor / Contenido')),
            ],
            options={
                'verbose_name': 'Dato Configurable',
                'verbose_name_plural': 'Datos Configurables',
            },
        ),
    ]
