# Generated by Django 6.0.3 on 2026-03-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0012_datosconfigurables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosconfigurables',
            name='valor',
            field=models.CharField(max_length=150, verbose_name='Valor / Contenido'),
        ),
    ]
