# Generated by Django 6.0.3 on 2026-03-16 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0013_alter_datosconfigurables_valor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conceptofacturable',
            options={},
        ),
        migrations.RemoveField(
            model_name='conceptofacturable',
            name='texto_adicional',
        ),
        migrations.AddField(
            model_name='conceptofacturable',
            name='cantidad_adicional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='conceptofacturable',
            name='cantidad_base_incluida',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='conceptofacturable',
            name='descripcion_adicional',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conceptofacturable',
            name='envase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajustes.tipoenvase'),
        ),
        migrations.AddField(
            model_name='conceptofacturable',
            name='info_adicional',
            field=models.BooleanField(default=False, verbose_name='¿Tiene info adicional?'),
        ),
        migrations.AddField(
            model_name='conceptofacturable',
            name='residuo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajustes.tiporesiduo'),
        ),
        migrations.AddField(
            model_name='conceptofacturable',
            name='tipo_concepto',
            field=models.CharField(choices=[('General', 'General'), ('Envase', 'Envase'), ('Residuo', 'Residuo')], default='General', max_length=10),
        ),
        migrations.AlterField(
            model_name='conceptofacturable',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='conceptofacturable',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='conceptofacturable',
            name='precio_adicional',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
