# Generated by Django 6.0.3 on 2026-03-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0014_alter_conceptofacturable_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptofacturable',
            name='cantidad_adicional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Unidades por bloque adicional (kg, envases, etc.)'),
        ),
        migrations.AlterField(
            model_name='conceptofacturable',
            name='cantidad_base_incluida',
            field=models.IntegerField(default=1, verbose_name='Cantidad incluida en el precio base (kg, envases, etc.)'),
        ),
        migrations.AlterField(
            model_name='conceptofacturable',
            name='descripcion_adicional',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción de la tarificación adicional'),
        ),
        migrations.AlterField(
            model_name='conceptofacturable',
            name='info_adicional',
            field=models.BooleanField(default=False, verbose_name='¿Tiene tarificación adicional?'),
        ),
        migrations.AlterField(
            model_name='conceptofacturable',
            name='precio_adicional',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Precio bloque adicional (€)'),
        ),
        migrations.AlterField(
            model_name='conceptofacturable',
            name='precio_base',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Precio del servicio base (€)'),
        ),
    ]
