PROVINCIAS_CHOICES = [
    ('Alava', 'Álava'), ('Albacete', 'Albacete'), ('Alicante', 'Alicante'),
    ('Almeria', 'Almería'), ('Asturias', 'Asturias'), ('Avila', 'Ávila'),
    ('Badajoz', 'Badajoz'), ('Barcelona', 'Barcelona'), ('Burgos', 'Burgos'),
    ('Caceres', 'Cáceres'), ('Cadiz', 'Cádiz'), ('Cantabria', 'Cantabria'),
    ('Castellon', 'Castellón'), ('Ciudad Real', 'Ciudad Real'), ('Cordoba', 'Córdoba'),
    ('La Coruña', 'La Coruña'), ('Cuenca', 'Cuenca'), ('Gerona', 'Gerona'),
    ('Granada', 'Granada'), ('Guadalajara', 'Guadalajara'), ('Guipuzcoa', 'Guipúzcoa'),
    ('Huelva', 'Huelva'), ('Huesca', 'Huesca'), ('Islas Baleares', 'Islas Baleares'),
    ('Jaen', 'Jaén'), ('Leon', 'León'), ('Lerida', 'Lérida'), ('Lugo', 'Lugo'),
    ('Madrid', 'Madrid'), ('Malaga', 'Málaga'), ('Murcia', 'Murcia'),
    ('Navarra', 'Navarra'), ('Orense', 'Orense'), ('Palencia', 'Palencia'),
    ('Las Palmas', 'Las Palmas'), ('Pontevedra', 'Pontevedra'), ('La Rioja', 'La Rioja'),
    ('Salamanca', 'Salamanca'), ('Segovia', 'Segovia'), ('Sevilla', 'Sevilla'),
    ('Soria', 'Soria'), ('Tarragona', 'Tarragona'), ('Santa Cruz de Tenerife', 'Santa Cruz de Tenerife'),
    ('Teruel', 'Teruel'), ('Toledo', 'Toledo'), ('Valencia', 'Valencia'),
    ('Valladolid', 'Valladolid'), ('Vizcaya', 'Vizcaya'), ('Zamora', 'Zamora'),
    ('Zaragoza', 'Zaragoza'), ('Ceuta', 'Ceuta'), ('Melilla', 'Melilla'),
]
