"""
Django settings for configuracion project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*16!d79tenqo_2k&2-br8l3p8)-3h-9e_%dj)t(0j(x@6&d!dg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['eco.developersasapglobalsolution.com', 'localhost', '127.0.0.1']

CSRF_TRUSTED_ORIGINS = [
    'https://eco.developersasapglobalsolution.com',
    'http://eco.developersasapglobalsolution.com',
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Application definition

INSTALLED_APPS = [
    'jazzmin',  # <--- IMPORTANTE: Siempre antes que admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'ajustes',
    'logistica',
    'gestion_residuos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'configuracion.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'configuracion.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'ecoefforts_db',   # Crea esta DB en phpMyAdmin de MAMP
#         'USER': 'root',
#         'PASSWORD': 'root',        # En MAMP la clave suele ser 'root'
#         'HOST': '127.0.0.1',
#         'PORT': '8889',            # Revisa en MAMP si usas 3306 u 8889
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-es'  # Cambia 'en-us' por 'es-es'

TIME_ZONE = 'Europe/Madrid'  # O tu zona horaria local

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

JAZZMIN_SETTINGS = {
    "site_title": "EcoEfforts Admin",
    "site_header": "EcoEfforts",
    "site_brand": "EcoEfforts Logística",
    "welcome_sign": "Bienvenido al Panel de Gestión de EcoEfforts",
    "copyright": "EcoEfforts",
    "user_avatar": None,
    # Activa el buscador, paginación y ordenación dinámica en el cliente
    "show_ui_builder": False, 
    "changeform_format": "horizontal_tabs",
    
    # Esto es clave para que las tablas sean dinámicas
    "use_google_fonts": True,
    "navigation_expanded": False,  # Las secciones empiezan contraídas
    
    # --- MENÚ LATERAL TIPO ACORDEÓN ---
    "show_sidebar": True,
    "sidebar_nav_child_indent": True, # Activa la sangría para los modelos
    
    # Orden de las cabeceras principales
    "order_with_respect_to": [
        "auth",
        "ajustes", 
        "ajustes.DatosConfigurables", # Supongamos que quieres este el primero
        "ajustes.Zona",
        "ajustes.TipoResiduo",
        "ajustes.TipoEnvase",
        "ajustes.ConceptoFacturable",
        "ajustes.Impuesto",
        "ajustes.Periodicidad",
        "ajustes.FechaPago",
        "logistica",    
        "logistica.cliente",
        "logistica.subcliente",    
        "logistica.puntorecogida",
        "logistica.transportista",
        "logistica.vehiculo",
        "logistica.gestorresiduos",
        "gestion_residuos",  
    ],
    "icons": {
        "auth": "fas fa-shield",
        "auth.user": "fas fa-user-shield",
        "auth.group": "fas fa-users-cog",
        "ajustes": "fas fa-cog",
        "ajustes.zona": "fas fa-map-marker-alt",
        "ajustes.fechapago": "fas fa-calendar-alt",
        "ajustes.impuesto": "fas fa-percentage",
        "ajustes.periodicidad": "fas fa-redo-alt",
        "ajustes.conceptofacturable": "fas fa-tag",
        "ajustes.tipoenvase": "fas fa-box",
        "ajustes.tiporesiduo": "fas fa-recycle",
        "ajustes.datosconfigurables": "fas fa-key",
        "logistica": "fas fa-truck-loading",
        "logistica.transportista": "fas fa-truck",
        "logistica.vehiculo": "fas fa-shuttle-van",
        "logistica.gestorresiduos": "fas fa-industry",
        "logistica.cliente": "fas fa-briefcase",
        "logistica.subcliente": "fas fa-users-cog",
        "logistica.puntorecogida": "fas fa-user-tag",
        "gestion_residuos": "fas fa-shuttle-van",
    },

    "model_aliases": {
        "auth.user": "Usuarios del Panel",
        "auth.group": "Roles",
    },

    "custom_css": "css/custom_admin.css",
    "custom_js": "js/cliente_admin.js",

}

# Opcional: Cambiar el tema de color a uno más moderno (estilo AdminLTE oscuro o claro)
JAZZMIN_UI_SETTINGS = {
    "theme": "flatly", # Temas: flatly, darkly, slate, lumen, etc.
    "dark_mode_theme": "darkly",
}

# Añadimos configuración de interfaz (UI Customizer) para que las tablas se vean mejor
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark-primary",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
}

STATIC_URL = 'static/'

# Esta es la línea que te falta:
# Indica la carpeta donde se reunirán todos los estáticos para producción
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 

# Asegúrate de tener también configurada la carpeta de origen de tus archivos
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
