# Generated by Django 6.0.3 on 2026-03-16 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ajustes', '0013_alter_datosconfigurables_valor'),
        ('logistica', '0010_puntorecogida_gestor_puntorecogida_transportista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(editable=False, max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('periodicidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ajustes.periodicidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.cliente', verbose_name='Usuario/Cliente')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='LineaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.CharField(blank=True, max_length=255, null=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ajustes.conceptofacturable')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='operativa.servicio')),
            ],
            options={
                'verbose_name': 'Línea de Servicio',
                'verbose_name_plural': 'Líneas de Servicio',
            },
        ),
    ]
