# Generated by Django 6.0.3 on 2026-03-17 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0015_alter_conceptofacturable_cantidad_adicional_and_more'),
        ('operativa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='periodicidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ajustes.periodicidad', verbose_name='Periodicidad'),
        ),
    ]
