# Generated by Django 6.0.3 on 2026-03-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativa', '0002_alter_servicio_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineaservicio',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
