# Generated by Django 6.0.3 on 2026-03-17 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0015_alter_conceptofacturable_cantidad_adicional_and_more'),
        ('logistica', '0010_puntorecogida_gestor_puntorecogida_transportista'),
        ('operativa', '0003_alter_lineaservicio_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.puntorecogida', verbose_name='Usuario/Punto de Recogida'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistica.gestorresiduos')),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='operativa.servicio')),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistica.transportista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.puntorecogida')),
            ],
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.CharField(blank=True, max_length=255, null=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ajustes.conceptofacturable')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='operativa.pedido')),
            ],
        ),
    ]
