# Generated by Django 6.0.3 on 2026-03-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativa', '0004_alter_servicio_usuario_pedido_lineapedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_ejecucion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
