# Generated by Django 6.0.3 on 2026-03-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativa', '0005_pedido_fecha_ejecucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_ejecucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de ejecución'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_programada',
            field=models.DateField(editable=False),
        ),
    ]
