# Generated by Django 6.0.3 on 2026-03-17 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativa', '0006_alter_pedido_fecha_ejecucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='operativa.servicio'),
        ),
    ]
