# Generated by Django 6.0.3 on 2026-03-17 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativa', '0007_alter_pedido_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='cantidad_recogida',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='observaciones_recogida',
            field=models.TextField(blank=True, null=True, verbose_name='Incidencias/Notas de recogida'),
        ),
        migrations.CreateModel(
            name='Albaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=30, unique=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='albaran', to='operativa.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='albaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_albaran', to='operativa.albaran'),
        ),
    ]
