# Generated by Django 6.0.3 on 2026-03-18 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operativa', '0008_lineapedido_cantidad_recogida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaAlbaranProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Línea de Albarán',
                'verbose_name_plural': 'Líneas de Albarán',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('operativa.lineapedido',),
        ),
        migrations.AlterModelOptions(
            name='albaran',
            options={'verbose_name': 'Albarán', 'verbose_name_plural': 'Albaranes'},
        ),
    ]
