# Generated by Django 6.0.3 on 2026-03-18 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0010_puntorecogida_gestor_puntorecogida_transportista'),
        ('operativa', '0009_lineaalbaranproxy_alter_albaran_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='albaran',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistica.vehiculo', verbose_name='Vehículo de recogida'),
        ),
    ]
