# Generated by Django 6.0.3 on 2026-03-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativa', '0010_albaran_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='albaran',
            name='fecha_ejecucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de ejecución'),
        ),
        migrations.AlterField(
            model_name='albaran',
            name='fecha_emision',
            field=models.DateField(verbose_name='Fecha de emisión'),
        ),
    ]
