# Generated by Django 6.0.3 on 2026-03-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativa', '0011_albaran_fecha_ejecucion_alter_albaran_fecha_emision'),
    ]

    operations = [
        migrations.AddField(
            model_name='albaran',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones del Servicio'),
        ),
    ]
