# Generated by Django 6.0.3 on 2026-03-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativa', '0012_albaran_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineapedido',
            name='observaciones_recogida',
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='notas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Incidencias/Notas de recogida'),
        ),
    ]
